# Generated by Django 4.2.1 on 2023-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_alter_icecream_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Зображення'),
        ),
    ]
