# Generated by Django 4.2.3 on 2023-07-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0007_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='image',
        ),
    ]
